#!/usr/bin/with-contenv bash
# vim: ft=bash
# shellcheck shell=bash
# ==============================================================================
# Start OpenThread BorderRouter web interface
# ==============================================================================
. /etc/s6-overlay/scripts/hassio_compat.sh
log_info "Starting otbr-web..."
declare otbr_web_port

otbr_web_port="$(addon_port 8080)"

exec stdbuf -oL /usr/sbin/otbr-web -I wpan0 -d6 -s -a "::" -p "${otbr_web_port}"
