#!/usr/bin/with-contenv bash
# vim: ft=bash
# shellcheck shell=bash
# ==============================================================================
# Start OpenThread BorderRouter web interface
# ==============================================================================
# shellcheck source=./rootfs/etc/s6-overlay/scripts/otbr-agent-common
. /etc/s6-overlay/scripts/otbr-agent-common

log_info "Starting otbr-web..."
declare otbr_web_port
declare otbr_log_level_int

otbr_web_port="$(addon_port 8080)"
otbr_log_level_int="$(otbr_log_level_to_int)" \
    || exit_nok "Unknown otbr_log_level: $(config_get otbr_log_level)"

exec stdbuf -oL /usr/sbin/otbr-web -I wpan0 -d"${otbr_log_level_int}" -s -a "::" -p "${otbr_web_port}"
