#!/usr/bin/with-contenv bash
# vim: ft=bash
# shellcheck shell=bash
#==============================================================================
# mDNSResponder finish script
#==============================================================================
. /etc/s6-overlay/scripts/hassio_compat.sh
log_info "mDNS ended with exit code ${1} (signal ${2})..."
